server:
  port: 9000

spring:

  resources:
  static:
  locations: classpath:/static/,classpath:/public/,file:./build/


  thymeleaf:
    prefix: classpath:/templates/

  application:
    name: demo

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-n2ma7-kr.vpc-pub-cdb.ntruss.com:3306/together?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: possible12
    password: final12345!

  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.together.mapper